---

# making sure the package's bin actually exists
- name: "Stats over {{ nvm_dir }}/versions/node/v{{ nvm_node_version }}/bin/{{ item.name }}"
  stat:
    path: "{{ nvm_dir }}/versions/node/v{{ nvm_node_version }}/bin/{{ item.name }}"
  register: package_stats_1
  when: item.name is defined

- name: Symlink global packages into PATH for specific environments (like cron's) to be able to access them.
  file: src="{{ nvm_dir }}/versions/node/v{{ nvm_node_version }}/bin/{{ item.name }}"
        dest="/usr/bin/{{ item.name }}" state=link mode="u+rwx,g+rx,o+rx"
  when: item.name is defined and package_stats_1.stat.exists

- name: "Stats over {{ nvm_dir }}/versions/node/v{{ nvm_node_version }}/bin/{{ item }}"
  stat:
    path: "{{ nvm_dir }}/versions/node/v{{ nvm_node_version }}/bin/{{ item }}"
  register: package_stats_2
  when: item.name is not defined

- name: Symlink global packages into PATH for specific environments (like cron's) to be able to access them.
  file: src="{{ nvm_dir }}/versions/node/v{{ nvm_node_version }}/bin/{{ item }}"
        dest="/usr/bin/{{ item }}" state=link mode="u+rwx,g+rx,o+rx"
  when: item.name is not defined and package_stats_2.stat.exists
